version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "scrumblr-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fyd2luqm0fmg"
s3_prefix = "scrumblr-api"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "scrumblr-api-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1blk0fddz2s9z"
s3_prefix = "scrumblr-api-stack"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
profile = "scrumblr"
