AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  scrumblr-app

  Sample SAM Template for scrumblr-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 600
    Environment:
      Variables:
        TABLE_BOARD: Board
        TABLE_WEBSOCKET: WebsocketConnections
        INDEX_BOARDID_CONNECTIONS: Sort-BoardId-ConnectionId-GSI

Resources:
  ScrumblrApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      BinaryMediaTypes: ['*/*']

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: scrumblr-api/
      Handler: lambda.handler
      Runtime: nodejs14.x
      # VpcConfig:
      #   SubnetIds:
      #     - !Ref LambdaSubnet
      #   SecurityGroupIds:
      #     - !Ref LambdaSecurityGroup
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref ScrumblrApi
            Path: '/{proxy+}'
            Method: ANY
      Policies:
        - AmazonDynamoDBFullAccess

  WebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: scrumblrWebSocket
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.action

  DefaultFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: websockets/default
      Handler: default.handler
      Timeout: 30
      Runtime: nodejs14.x
      Policies:
        - AWSLambda_FullAccess
        - CloudWatchLogsFullAccess
        - AmazonAPIGatewayInvokeFullAccess
        - AmazonAPIGatewayAdministrator
        - AmazonDynamoDBFullAccess
  DefaultLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebSocketApi
      - DefaultFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref DefaultFunction
      Principal: apigateway.amazonaws.com

  DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $default
      AuthorizationType: NONE
      OperationName: DefaultRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref DefaultIntegration
  DefaultIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      Description: Default Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DefaultFunction.Arn}/invocations

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $connect
      AuthorizationType: NONE
      OperationName: ConnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref ConnectIntegration
  ConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      Description: Connect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketConnectHandlerFunction.Arn}/invocations
  WebSocketConnectHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: websockets/onconnect
      Handler: onconnect.handler
      Timeout: 30
      Runtime: nodejs14.x
      Environment:
        Variables:
          TABLE_BOARD: Board
          TABLE_WEBSOCKET: WebsocketConnections
          INDEX_BOARDID_CONNECTIONS: Sort-BoardId-ConnectionId-GSI
      Policies:
        - AWSLambda_FullAccess
        - CloudWatchLogsFullAccess
        - AmazonAPIGatewayInvokeFullAccess
        - AmazonAPIGatewayAdministrator
        - AmazonDynamoDBFullAccess
  WebsocketConnectLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebSocketApi
      - WebSocketConnectHandlerFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WebSocketConnectHandlerFunction
      Principal: apigateway.amazonaws.com
  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $disconnect
      AuthorizationType: NONE
      OperationName: DisconnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref DisconnectIntegration
  DisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      Description: Disconnect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketDisconnectHandlerFunction.Arn}/invocations
  WebSocketDisconnectHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: websockets/ondisconnect
      Handler: ondisconnect.handler
      MemorySize: 256
      Runtime: nodejs14.x
      Environment:
        Variables:
          TABLE_BOARD: Board
          TABLE_WEBSOCKET: WebsocketConnections
          INDEX_BOARDID_CONNECTIONS: Sort-BoardId-ConnectionId-GSI
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref WebSocketConnectTable
  WebsocketDisconnectLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebSocketApi
      - WebSocketDisconnectHandlerFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WebSocketDisconnectHandlerFunction
      Principal: apigateway.amazonaws.com

  # VPC:
  #   Type: AWS::EC2::VPC
  #   Properties:
  #     CidrBlock: 10.0.0.0/16

  # InternetGateway:
  #   Type: AWS::EC2::InternetGateway

  # VPCGatewayAttachment:
  #   Type: AWS::EC2::VPCGatewayAttachment
  #   Properties:
  #     InternetGatewayId: !Ref InternetGateway
  #     VpcId: !Ref VPC

  # PublicSubnet:
  #   Type: AWS::EC2::Subnet
  #   Properties:
  #     VpcId: !Ref VPC
  #     CidrBlock: 10.0.1.0/28
  #     AvailabilityZone: !Select
  #       - 0
  #       - !GetAZs
  #         Ref: AWS::Region

  # LambdaSubnet:
  #   Type: AWS::EC2::Subnet
  #   Properties:
  #     VpcId: !Ref VPC
  #     CidrBlock: 10.0.128.0/20
  #     AvailabilityZone: !Select
  #       - 1
  #       - !GetAZs
  #         Ref: AWS::Region

  # NatGatewayEIP:
  #   Type: AWS::EC2::EIP
  #   Properties:
  #     Domain: vpc

  # NatGateway:
  #   Type: AWS::EC2::NatGateway
  #   Properties:
  #     SubnetId: !Ref PublicSubnet
  #     AllocationId: !GetAtt NatGatewayEIP.AllocationId

  # PublicRouteTable:
  #   Type: AWS::EC2::RouteTable
  #   Properties:
  #     VpcId: !Ref VPC

  # PublicRTAssociation:
  #   Type: AWS::EC2::SubnetRouteTableAssociation
  #   Properties:
  #     RouteTableId: !Ref PublicRouteTable
  #     SubnetId: !Ref PublicSubnet

  # LambdaRouteTable:
  #   Type: AWS::EC2::RouteTable
  #   Properties:
  #     VpcId: !Ref VPC

  # LambdaRouteTableAssociation:
  #   Type: AWS::EC2::SubnetRouteTableAssociation
  #   Properties:
  #     RouteTableId: !Ref LambdaRouteTable
  #     SubnetId: !Ref LambdaSubnet

  # InternetRoute:
  #   Type: AWS::EC2::Route
  #   Properties:
  #     RouteTableId: !Ref PublicRouteTable
  #     DestinationCidrBlock: 0.0.0.0/0
  #     GatewayId: !Ref InternetGateway

  # NatGatewayRoute:
  #   Type: AWS::EC2::Route
  #   Properties:
  #     RouteTableId: !Ref LambdaRouteTable
  #     DestinationCidrBlock: 0.0.0.0/0
  #     NatGatewayId: !Ref NatGateway

  # LambdaSecurityGroup:
  #   Type: AWS::EC2::SecurityGroup
  #   Properties:
  #     GroupDescription: Open Lambda ports
  #     VpcId: !Ref VPC
  #     SecurityGroupIngress:
  #       - CidrIp: 0.0.0.0/0
  #         FromPort: 80
  #         ToPort: 80
  #         IpProtocol: tcp
  #       - CidrIp: 0.0.0.0/0
  #         FromPort: 443
  #         ToPort: 443
  #         IpProtocol: tcp

  ScrumblrTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Board
      AttributeDefinitions:
        - AttributeName: BoardId
          AttributeType: S
        - AttributeName: BoardName
          AttributeType: S
      KeySchema:
        - AttributeName: BoardId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: BoardNameGSI
          KeySchema:
            - AttributeName: BoardName
              KeyType: HASH
          Projection:
            NonKeyAttributes:
              - board_notes
            ProjectionType: INCLUDE
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
  WebSocketConnectTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: WebsocketConnections
      AttributeDefinitions:
        - AttributeName: ConnectionId
          AttributeType: S
        - AttributeName: BoardId
          AttributeType: S
      KeySchema:
        - AttributeName: ConnectionId
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: TimeToLive
        Enabled: true
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: Sort-BoardId-ConnectionId-GSI
          KeySchema:
            - AttributeName: BoardId
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - ConnectRoute
      - DisconnectRoute
      - DefaultRoute
    Properties:
      ApiId: !Ref WebSocketApi

  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref WebSocketApi
      StageName: prod
      DeploymentId: !Ref Deployment

  ScrumblrFrontend:
    Type: AWS::S3::Bucket
    Description: Creating Amazon S3 bucket from CloudFormation
    Properties:
      BucketName: scrumblr-frontend

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: 'API Gateway endpoint URL for Prod stage for Hello World function'
    Value: !Sub 'https://${ScrumblrApi}.execute-api.${AWS::Region}.amazonaws.com/prod/'
  HelloWorldFunction:
    Description: 'Hello World Lambda Function ARN'
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: 'Implicit IAM Role created for Hello World function'
    Value: !GetAtt HelloWorldFunctionRole.Arn
